language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "I9tETOtv7moOjI0vfMaB4LvVTeUbTfRZsTLOEDfaVZhIwNHtCvDAapr2/TDVv0zM4/eZ7qWNO3vMVwsHFLsjfrKOxEFukizECWfl6EtFupC19IniBD+tbFij8OHdA0GVs9eCHeF4QGVoB8iCdlT4c94xKH/z0UK0guCf9B1NTqz+T3zfXCpgy6U4AMmNi5NAW9mCWcFUpLQ6KF3tvIvy29v9nCWNebYC65qg9XL37O5MKlhcugth33aBX7e5yH5ehY0e6BIvzxgxLkeD7YwEwKzduQWdmqADxRl8UgudMuHj1IvwCYgVa1EAI8zhwU7CuUmHIJms5veB3R6rThC884Wcmu7wWYkvNuOsyb2Z8lpjI+2jHSrN7MXJeLRcj+oQbGas7VTjqJ+R6gTrRjnv9v+skja6hLcDVFDzOTh0h5BqBhmR1blU7xI1s8U2zkA1mmNzCF/ZeQudoFaOZI68CpxqsiT4WOsbeD8XX0QcNuQ1SzvigueTgdOtmZpOW0OB2G1AS3D90jqm72m23gS+uQpr/9kDII/urLz2z2sJPQ6ZnQ5h6zK4NwCq2oxxS9uCNyagTfbNXBaG7js/xyoYpsuzfAktWYT5oFWOHOMdjYZlR2r4BEDy6ua7KP19Nu4Q2G4CCLONDqdcpa7CNZrlCTBUlr69A01z5PZkgsgqFAw="
